# Site settings
title: prateek sachan
email: ps@prateeksachan.com
timezone: Asia/Kolkata
copyright: "&copy; 2017 Prateek Sachan."
description: "Prateek Sachan is a web application developer based in Delhi, India working on PHP, Javascript, Python, Elasticsearch, Solr"
keywords: "Prateek Sachan, web application developer, Delhi, Zomato, PHP, Solr, Drupal, Moodle, Elasticsearch, IIT Delhi, Indian Institute of Technology Delhi"
baseurl: ""
url: "http://prateeksachan.com"
twitter_username: xan_ps
github_username:  prateeksachan
instagram_username: xan_ps
facebook_username: prateek.sachan
google_site_verification: "A7zEpGpTiYAJHdFcaP9k_M5me1NhYBckQC7VuQfATfg"
author:
    twitter: xan_ps

#links
jeykll_link: http://jekyllrb.com/
vim_link: http://www.vim.org/

# Build settings
markdown: kramdown

#paginate: 5
#paginate_path: '/blog/page:num'
#permalink: /blog/:year/:month/:day/:title/

pagination:
  enabled: true
  per_page: 5
  paginate_path: '/blog/page:num'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true


#social media
sharing:
    provider: tweet
    twitter:
        size:
        via: xan_ps
        count:

#sitemap
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - instagram

autopages:
  enabled: true

  # Category pages, omit entire config element to disable
  categories: 
    enabled: false

  # Collection pages, omit to disable
  collections:
    enabled: false

  # Tag pages, omit to disable
  tags:
    layouts: 
      - 'tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
