# Site settings
title: prateek sachan
email: ps@prateeksachan.com
timezone: Asia/Kolkata
copyright: > # this means to ignore newlines until "baseurl:"
  &copy; 2014 Prateek Sachan.

description: "Prateek Sachan is a web application developer based in Delhi, India working on PHP, Javascript, Python, Solr"
keywords: "Prateek Sachan, web application developer, Delhi, Zomato, PHP, Solr, Drupal, Moodle, Elasticsearch, IIT Delhi, Indian Institute of Technology Delhi"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prateeksachan.com" # the base hostname & protocol for your site
twitter_username: xan_ps
github_username:  prateeksachan
instagram_username: xan_ps
facebook_username: prateek.sachan
author:
    twitter: xan_ps

#links
jeykll_link: http://jekyllrb.com/
vim_link: http://www.vim.org/
# Build settings
markdown: kramdown
paginate: 5
paginate_path: 'blog/page:num'
permalink: /blog/:year/:month/:day/:title/
sharing:
    provider: tweet
    twitter:
        size:
        via: xan_ps
        count:
